"""Removed name. Added phone number

Revision ID: b880b9ad3f8d
Revises: f43788429373
Create Date: 2024-05-16 13:39:57.853856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b880b9ad3f8d'
down_revision = 'f43788429373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MpesaReceiptNumber', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('Amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('TransactionDate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('PhoneNumber', sa.Integer(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('contact')
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('PhoneNumber')
        batch_op.drop_column('TransactionDate')
        batch_op.drop_column('Amount')
        batch_op.drop_column('MpesaReceiptNumber')

    # ### end Alembic commands ###
